import 'package:flutter/material.dart';

import '../models/food.dart';

class MyTabBar extends StatelessWidget {
  final TabController tabController;

  const MyTabBar({
    super.key,
    required this.tabController,
  });

  // Helper function to build category tabs from the FoodCategory enum
  List<Tab> _buildCategoryTabs() {
    // Using the values from the FoodCategory enum to create a list of Tab widgets
    return FoodCategory.values.map((category) {
      // Each tab text is generated by converting the enum value to string and taking the part after the dot
      return Tab(
        text: category.toString().split('.').last,
      );
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    // Builds a container that holds a TabBar
    return Container(
      child: TabBar(
        controller: tabController,
        tabs: _buildCategoryTabs(), // Building tabs using the _buildCategoryTabs function
      ),
    );
  }
}
